// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skynet.Infrastructure.Persistence;

namespace Skynet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181111132734_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Skynet.Domain.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlobId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<Guid>("RobotId");

                    b.HasKey("Id");

                    b.HasIndex("RobotId");

                    b.ToTable("Captures","Skynet");
                });

            modelBuilder.Entity("Skynet.Domain.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Model");

                    b.HasKey("Id");

                    b.ToTable("Robots","Skynet");

                    b.HasData(
                        new { Id = new Guid("8d225a2f-2bed-45a6-ae73-b756e1528948"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 8 },
                        new { Id = new Guid("53386d46-fe61-4487-89f0-29664276c3a6"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 0 },
                        new { Id = new Guid("40860581-1be3-4f28-b131-96ad5fb65d23"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 11 },
                        new { Id = new Guid("2cc291e3-2930-4cbf-affa-e820ffd56cff"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 12 },
                        new { Id = new Guid("aa90f569-ca56-440c-beee-5fc951921992"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 4 },
                        new { Id = new Guid("bb0296d1-0482-4ff8-a7c3-d856feb1eed6"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 5 },
                        new { Id = new Guid("801c58bc-4a32-42fd-b536-2672513db4de"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 7 },
                        new { Id = new Guid("7b851a63-c544-4fad-a015-6204a3da66ad"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 14 },
                        new { Id = new Guid("605d763e-72f4-4009-bfd7-165508523256"), Created = new DateTime(2018, 11, 11, 13, 27, 34, 332, DateTimeKind.Utc), Model = 1 }
                    );
                });

            modelBuilder.Entity("Skynet.Domain.Capture", b =>
                {
                    b.HasOne("Skynet.Domain.Robot", "Robot")
                        .WithMany("Captures")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
